### ISSUE TITLE
Support tracking minutes?

### ISSUE THREAD

**Issue by jurre** [DefactoSoftware/Hours#163]
Currently _Hours_ only supports tracking full hours (hence the name) but we've gotten a few requests to support minutes.

Personally we feel that tracking anything less than a full hour is just not worth it, it doesn't provide any insight and we're not using Hours to directly bill to our customers.

We'd love to hear other people's thoughts on this.

One consequence would be that we'd have to rename the app to _Minutes_ though ;)

**Comment by ameenross** [comment]
@jurre I see where those concerns are coming from, but hour registration is inherently a trust issue. Someone could be staring at his screen for one hour, glance at his phone for another hour and then code the third hour, while registering 3 hours of productive work. That's why I don't see a lot of value in constraining users to the projects they're actually assigned to etc.

Besides that, in some cases all those 20-30 minute coding sessions for a particular side project can add up over time and be useful to track, even if only for insight. You don't need to show fractions of hours in your reports (except the detailed reports) and you don't need to *require* inputting minutes, so it doesn't really make timetracking more labor intensive. I don't see any advantage in not being able to enter time with higher granularity, even for insight.

For a nice implementation I'd look at Harvest. They support both `1.5` and `1:30` as input to mean `1 hour and 30 minutes`. In terms of time spent entering time it works fine.

**Comment by emragins** [comment]
Hmm.... 2 years later and no progress on this?  Sad because this is the deal-breaker for me.  I need to be able to store at least quarter hours.  Non-integer values (such as 7.25) would have been fine.  

To help you understand, I track time for billing.  Not so granular where I need to track "10 minutes here" but "7.5 hours today, 8.5 hours tomorrow, 6 on wednesday", etc.  Rounding would throw it off a lot (and look really weird when we export for approval...)

**Comment by jurre** [comment]
> Hmm.... 2 years later and no progress on this?

What do you mean "progress"? It's a feature we have decided we do not want to support.

> To help you understand, I track time for billing.

Hours is probably not the right tool for you, maybe look at something like https://letsfreckle.com

**Comment by ameenross** [comment]
I'd have at least expected some rebuttal of my comment, especially as you yourself opened this issue with the following note:

> We'd love to hear other people's thoughts on this.

**Comment by jurre** [comment]
Hey @ameenross

We created Hours with the very specific intent to gain insight on how our team was spending time, there are plenty of other great apps, like Harvest as you mentioned, that support tracking  time for supervision.

If you work in a team and you spend 20 minutes patching some server, I don't think it's a valuable thing to know when looking at the big picture. If you spend 20 minutes a day on it and you think it's super important for the big picture, you could track it as an hour once a week.

The thing is that while minutes don't require extra work to *enter*, it does increase the burden when thinking about what you did the previous day (or a couple of days ago, since we've seen most people will enter their entire week on Fridays), and it'll be hardly any more accurate over the long run.

We found that having people not think about their time in such small units forces them to look at the big picture of what they were doing that day or week, and this has proven more useful for us.

I should have probably closed the issue sooner and replied to your comment :)
